set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# ---- C compiler from environment ----
separate_arguments(CC_LIST NATIVE_COMMAND "$ENV{CC}")
list(GET CC_LIST 0 C_COMPILER)
list(REMOVE_AT CC_LIST 0)
string(JOIN " " C_FLAGS_FROM_ENV ${CC_LIST})

set(CMAKE_C_COMPILER "${C_COMPILER}")
set(CMAKE_C_FLAGS_INIT "${C_FLAGS_FROM_ENV}")

# ---- C++ compiler from environment ----
separate_arguments(CXX_LIST NATIVE_COMMAND "$ENV{CXX}")
list(GET CXX_LIST 0 CXX_COMPILER)
list(REMOVE_AT CXX_LIST 0)
string(JOIN " " CXX_FLAGS_FROM_ENV ${CXX_LIST})

set(CMAKE_CXX_COMPILER "${CXX_COMPILER}")
set(CMAKE_CXX_FLAGS_INIT "${CXX_FLAGS_FROM_ENV}")

# ---- Sysroot ----
set(CMAKE_SYSROOT "$ENV{SDKTARGETSYSROOT}")
set(CMAKE_FIND_ROOT_PATH "$ENV{SDKTARGETSYSROOT}")

# ---- Search behavior ----
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

