from pathlib import Path
import shutil

from .common import (
    Model,
    packed_default,
    sv_const,
    width_range,
)


def module_index(model: Model, name: str) -> int:
    return [module.name for module in model.modules].index(name)


def resource_index(model: Model, name: str) -> int:
    return model.pingpongs.index(name)


def split_deps(model: Model, deps: list[str]) -> tuple[list[str], list[str]]:
    module_names = {module.name for module in model.modules}
    mod_deps = []
    res_deps = []
    for dep in deps:
        if dep in module_names:
            mod_deps.append(dep)
        elif dep in model.pingpongs:
            res_deps.append(dep)
    return mod_deps, res_deps


def mask_for(model: Model, names: list[str], kind: str) -> int:
    mask = 0
    for name in names:
        idx = module_index(model, name) if kind == "module" else resource_index(model, name)
        mask |= 1 << idx
    return mask


def opcode_literal(model: Model, value: int) -> str:
    return f"{model.opcode_width}'h{value:0{max(1, (model.opcode_width + 3) // 4)}X}"


def int_literal(width: int, value: int) -> str:
    return f"{width}'d{value}"


def header() -> list[str]:
    return [
        "`timescale 1ns / 1ps",
        "// Auto-generated by scripts/gen_control.py. Edit the JSON spec, not this file.",
        "",
    ]


def emit_core(model: Model) -> str:
    mcount = len(model.modules)
    rcount = max(len(model.pingpongs), 1)
    lines = header()
    lines += [
        "module scheduler_core(",
        "    input  logic        clk,",
        "    input  logic        rst,",
        "",
        "    input  logic [31:0] axi_s_reg_bank,",
        "    output logic [31:0] axi_s_feed_back,",
        "    output logic        soft_rst,",
        "",
        "    output logic        ins_rd_start,",
        "    input  logic        ins_rd_done,",
        "    output logic        ins_fifo_rd_en,",
        "    input  logic        ins_fifo_n_empty,",
        f"    input  logic [{model.instruction_width - 1}:0] ins_fifo_data,",
        f"    output logic [{model.instruction_width - 1}:0] instruction,",
        "",
    ]
    for module in model.modules:
        if module.commands:
            lines.append(f"    output logic        issue_{module.name},")
    lines.append("    output logic        issue_regs,")
    lines.append("")
    done_ports = []
    for module in model.modules:
        if module.commands:
            done_ports.append(f"    input  logic        {module.name}_done")
    for idx, port in enumerate(done_ports):
        lines.append(port + ",")
    lines += [
        "    output logic        IRQ",
        ");",
        "",
        "    logic [7:0] hw_version = 8'd1;",
        "",
    ]
    for op in model.system_ops:
        lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_SYS_{sv_const(op.name)} = {opcode_literal(model, op.opcode)};")
    if model.regs_opcode is not None:
        lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_REGS = {opcode_literal(model, model.regs_opcode)};")
    for module in model.modules:
        if module.name in model.command_opcodes:
            lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_CMD_{sv_const(module.name)} = {opcode_literal(model, model.command_opcodes[module.name])};")
            for command in module.commands:
                lines.append(f"    localparam logic [{module.command_id_width - 1}:0] CMD_{sv_const(module.name, command.name)} = {int_literal(module.command_id_width, command.command_id)};")
    for module in model.modules:
        for reg in module.regs:
            lines.append(f"    localparam logic [{model.reg_addr_width - 1}:0] REG_{sv_const(module.name, reg.name)} = {int_literal(model.reg_addr_width, reg.addr)};")

    lines += [
        "",
        f"    wire [{model.opcode_width - 1}:0] opcode = instruction[{model.opcode_msb}:{model.opcode_lsb}];",
        f"    wire [{model.payload_width - 1}:0] payload = instruction[{model.payload_width - 1}:0];",
        f"    wire [{model.reg_addr_width - 1}:0] reg_addr = payload[{model.payload_width - 1}:{model.payload_width - model.reg_addr_width}];",
        "",
        "    logic [7:0] axi_s_reg_d;",
        "    logic [7:0] axi_s_event;",
        "    assign axi_s_event = (~axi_s_reg_d[7:0]) & axi_s_reg_bank[7:0];",
        "",
        "    always_ff @(posedge clk) begin",
        "        if (rst)",
        "            axi_s_reg_d <= '0;",
        "        else",
        "            axi_s_reg_d <= axi_s_reg_bank[7:0];",
        "    end",
        "",
        "    logic issue;",
        f"    logic [{mcount - 1}:0] module_busy;",
        f"    logic [{rcount - 1}:0] resource_busy;",
        f"    logic [{rcount - 1}:0] active_resource_mask [{mcount - 1}:0];",
        "",
        "    logic user_reset;",
        "    logic soft_reset_done;",
        "    soft_reset #(.BEATS(8)) soft_reset_u (",
        "        .clk(clk),",
        "        .reset(rst),",
        "        .start(axi_s_event[0]),",
        "        .done(soft_reset_done),",
        "        .user_reset(user_reset)",
        "    );",
        "    assign soft_rst = rst || user_reset;",
        "",
        "    logic __ins_rd_busy;",
        "    assign ins_rd_start = !__ins_rd_busy && axi_s_event[1] && !ins_fifo_n_empty;",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst) begin",
        "            __ins_rd_busy <= 1'b0;",
        "        end else begin",
        "            if (ins_rd_start)",
        "                __ins_rd_busy <= 1'b1;",
        "            else if (ins_rd_done)",
        "                __ins_rd_busy <= 1'b0;",
        "        end",
        "    end",
        "",
        "    logic instruction_valid;",
        "    logic new_instruction_in;",
        "    logic ins_fifo_rd_en_d;",
        "    assign new_instruction_in = ins_fifo_rd_en && ins_fifo_n_empty;",
        "    assign ins_fifo_rd_en = issue ? 1'b1 : ins_fifo_rd_en_d;",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst) begin",
        "            instruction <= '0;",
        "            instruction_valid <= 1'b0;",
        "            ins_fifo_rd_en_d <= 1'b1;",
        "        end else begin",
        "            if (new_instruction_in)",
        "                instruction <= ins_fifo_data;",
        "            if (new_instruction_in || issue) begin",
        "                instruction_valid <= new_instruction_in ? 1'b1 : !issue;",
        "                ins_fifo_rd_en_d <= new_instruction_in ? 1'b0 : issue;",
        "            end",
        "        end",
        "    end",
        "",
        f"    logic [{mcount - 1}:0] dep_module_mask;",
        f"    logic [{rcount - 1}:0] dep_resource_mask;",
        f"    logic [{rcount - 1}:0] use_resource_mask;",
        "    logic known_instruction;",
        "    integer i;",
        "",
        "    always @(*) begin",
        "        dep_module_mask = '0;",
        "        dep_resource_mask = '0;",
        "        use_resource_mask = '0;",
        "        known_instruction = 1'b1;",
        "        case (opcode)",
    ]
    for op in model.system_ops:
        mod_deps, res_deps = split_deps(model, op.deps)
        lines += [
            f"            OP_SYS_{sv_const(op.name)}: begin",
            f"                dep_module_mask = {mcount}'d{mask_for(model, mod_deps, 'module')};",
            f"                dep_resource_mask = {rcount}'d{mask_for(model, res_deps, 'resource')};",
            "            end",
        ]
    if model.regs_opcode is not None:
        lines += [
            "            OP_REGS: begin",
            "                case (reg_addr)",
        ]
        for module in model.modules:
            for reg in module.regs:
                lines.append(f"                    REG_{sv_const(module.name, reg.name)}: dep_module_mask = {mcount}'d{1 << module_index(model, module.name)};")
        lines += [
            "                    default: begin end",
            "                endcase",
            "            end",
        ]
    for module in model.modules:
        if not module.commands:
            continue
        lines += [
            f"            OP_CMD_{sv_const(module.name)}: begin",
            f"                dep_module_mask = {mcount}'d{1 << module_index(model, module.name)};",
            f"                case (payload[{model.payload_width - 1}:{model.payload_width - module.command_id_width}])",
        ]
        for command in module.commands:
            mod_deps, res_deps = split_deps(model, command.deps)
            dep_modules = list(dict.fromkeys([module.name] + mod_deps))
            dep_resources = list(dict.fromkeys(command.using + res_deps))
            lines += [
                f"                    CMD_{sv_const(module.name, command.name)}: begin",
                f"                        dep_module_mask = {mcount}'d{mask_for(model, dep_modules, 'module')};",
                f"                        dep_resource_mask = {rcount}'d{mask_for(model, dep_resources, 'resource')};",
                f"                        use_resource_mask = {rcount}'d{mask_for(model, command.using, 'resource')};",
                "                    end",
            ]
        lines += [
            "                    default: known_instruction = 1'b0;",
            "                endcase",
            "            end",
        ]
    lines += [
        "            default: known_instruction = 1'b0;",
        "        endcase",
        "    end",
        "",
        "    logic can_issue;",
        "    assign can_issue = known_instruction && ((dep_module_mask & module_busy) == '0) && ((dep_resource_mask & resource_busy) == '0);",
        "    assign issue = can_issue && instruction_valid;",
        "",
    ]
    for module in model.modules:
        if module.commands:
            lines.append(f"    assign issue_{module.name} = issue && opcode == OP_CMD_{sv_const(module.name)};")
    if model.regs_opcode is not None:
        lines.append("    assign issue_regs = issue && opcode == OP_REGS;")
    else:
        lines.append("    assign issue_regs = 1'b0;")
    lines += [
        "",
        f"    logic [{mcount - 1}:0] module_busy_next;",
        f"    logic [{rcount - 1}:0] resource_busy_next;",
        f"    logic [{rcount - 1}:0] active_resource_mask_next [{mcount - 1}:0];",
        "",
        "    always @(*) begin",
        "        module_busy_next = module_busy;",
        "        resource_busy_next = resource_busy;",
        "        for (i = 0; i < " + str(mcount) + "; i = i + 1)",
        "            active_resource_mask_next[i] = active_resource_mask[i];",
    ]
    for module in model.modules:
        if module.commands:
            idx = module_index(model, module.name)
            lines += [
                f"        if ({module.name}_done) begin",
                f"            module_busy_next[{idx}] = 1'b0;",
                f"            resource_busy_next = resource_busy_next & ~active_resource_mask[{idx}];",
                f"            active_resource_mask_next[{idx}] = '0;",
                "        end",
            ]
    for module in model.modules:
        if module.commands:
            idx = module_index(model, module.name)
            lines += [
                f"        if (issue_{module.name}) begin",
                f"            module_busy_next[{idx}] = 1'b1;",
                "            resource_busy_next = resource_busy_next | use_resource_mask;",
                f"            active_resource_mask_next[{idx}] = use_resource_mask;",
                "        end",
            ]
    lines += [
        "    end",
        "",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst) begin",
        "            module_busy <= '0;",
        "            resource_busy <= '0;",
        "            for (i = 0; i < " + str(mcount) + "; i = i + 1)",
        "                active_resource_mask[i] <= '0;",
        "        end else begin",
        "            module_busy <= module_busy_next;",
        "            resource_busy <= resource_busy_next;",
        "            for (i = 0; i < " + str(mcount) + "; i = i + 1)",
        "                active_resource_mask[i] <= active_resource_mask_next[i];",
        "        end",
        "    end",
        "",
        "    logic ins_fifo_n_empty_d;",
        "    logic program_done;",
        "    logic program_working;",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst)",
        "            ins_fifo_n_empty_d <= 1'b0;",
        "        else",
        "            ins_fifo_n_empty_d <= ins_fifo_n_empty;",
        "    end",
        "    assign program_done = ins_fifo_n_empty_d && !ins_fifo_n_empty;",
        "    assign program_working = __ins_rd_busy || instruction_valid || (module_busy != '0);",
        "",
        "    always @(*) begin",
        "        axi_s_feed_back = '0;",
        "        axi_s_feed_back[0] = soft_reset_done;",
        "        axi_s_feed_back[1] = program_done;",
        "        axi_s_feed_back[16] = program_working;",
        "        axi_s_feed_back[17] = user_reset;",
        "        axi_s_feed_back[31:24] = hw_version;",
        "    end",
        "",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst) begin",
        "            IRQ <= 1'b0;",
        "        end else begin",
        "            if (axi_s_event[2])",
        "                IRQ <= 1'b0;",
        "            else if (axi_s_reg_bank[8] && program_done)",
        "                IRQ <= 1'b1;",
        "        end",
        "    end",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def module_arg_width(module) -> int:
    if not module.commands:
        return 1
    return max(max(command.arg_width, 1) for command in module.commands)


def emit_wrapper(model: Model) -> str:
    lines = header()
    lines += [
        "module scheduler_wrapper(",
        "    input  logic        clk,",
        "    input  logic        rst,",
        "",
        "    input  logic        s_axi_aresetn,",
        "    input  logic [3:0]  s_axi_awaddr,",
        "    input  logic [2:0]  s_axi_awprot,",
        "    input  logic        s_axi_awvalid,",
        "    output logic        s_axi_awready,",
        "    input  logic [31:0] s_axi_wdata,",
        "    input  logic [3:0]  s_axi_wstrb,",
        "    input  logic        s_axi_wvalid,",
        "    output logic        s_axi_wready,",
        "    output logic [1:0]  s_axi_bresp,",
        "    output logic        s_axi_bvalid,",
        "    input  logic        s_axi_bready,",
        "    input  logic [3:0]  s_axi_araddr,",
        "    input  logic [2:0]  s_axi_arprot,",
        "    input  logic        s_axi_arvalid,",
        "    output logic        s_axi_arready,",
        "    output logic [31:0] s_axi_rdata,",
        "    output logic [1:0]  s_axi_rresp,",
        "    output logic        s_axi_rvalid,",
        "    input  logic        s_axi_rready,",
        "",
        "    output logic        soft_rst,",
        "    output logic        IRQ,",
        "",
        "    output logic        ins_rd_start,",
        "    input  logic        ins_rd_done,",
        "    output logic        ins_fifo_rd_en,",
        "    input  logic        ins_fifo_n_empty,",
        f"    input  logic [{model.instruction_width - 1}:0] ins_fifo_data,",
        f"    output logic [{model.instruction_width - 1}:0] instruction,",
        "",
    ]
    port_lines = []
    for module in model.modules:
        if module.commands:
            port_lines += [
                f"    output logic        {module.name}_ap_start",
                f"    input  logic        {module.name}_ap_ready",
                f"    input  logic        {module.name}_ap_done",
                f"    input  logic        {module.name}_ap_idle",
                f"    output logic {width_range(module.command_id_width)}{module.name}_cmd_id",
                f"    output logic {width_range(module_arg_width(module))}{module.name}_cmd_args",
            ]
        for reg in module.regs:
            port_lines.append(f"    output logic {width_range(reg.packed_width)}{module.name}_{reg.name}")
    lines.append(",\n".join(port_lines))
    lines += [
        ");",
        "",
    ]
    for op in model.system_ops:
        lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_SYS_{sv_const(op.name)} = {opcode_literal(model, op.opcode)};")
    if model.regs_opcode is not None:
        lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_REGS = {opcode_literal(model, model.regs_opcode)};")
    for module in model.modules:
        if module.name in model.command_opcodes:
            lines.append(f"    localparam logic [{model.opcode_width - 1}:0] OP_CMD_{sv_const(module.name)} = {opcode_literal(model, model.command_opcodes[module.name])};")
    for module in model.modules:
        for reg in module.regs:
            lines.append(f"    localparam logic [{model.reg_addr_width - 1}:0] REG_{sv_const(module.name, reg.name)} = {int_literal(model.reg_addr_width, reg.addr)};")
    lines += [
        "",
        f"    wire [{model.opcode_width - 1}:0] opcode = instruction[{model.opcode_msb}:{model.opcode_lsb}];",
        f"    wire [{model.payload_width - 1}:0] payload = instruction[{model.payload_width - 1}:0];",
        f"    wire [{model.reg_addr_width - 1}:0] reg_addr = payload[{model.payload_width - 1}:{model.payload_width - model.reg_addr_width}];",
        "",
    ]
    for module in model.modules:
        if module.commands:
            lines.append(f"    logic issue_{module.name};")
    lines += [
        "    logic issue_regs;",
        "    logic [31:0] axi_s_feed_back;",
        "    logic [127:0] axi_s_reg_bank;",
        "",
        "    scheduler_ctrl_axi_lite #(",
        "        .C_S_AXI_DATA_WIDTH(32),",
        "        .C_S_AXI_ADDR_WIDTH(4)",
        "    ) ctrl_axi_lite_u (",
        "        .FEED_BACK(axi_s_feed_back),",
        "        .AXI_REGS(axi_s_reg_bank),",
        "        .S_AXI_ACLK(clk),",
        "        .S_AXI_ARESETN(s_axi_aresetn),",
        "        .S_AXI_AWADDR(s_axi_awaddr),",
        "        .S_AXI_AWPROT(s_axi_awprot),",
        "        .S_AXI_AWVALID(s_axi_awvalid),",
        "        .S_AXI_AWREADY(s_axi_awready),",
        "        .S_AXI_WDATA(s_axi_wdata),",
        "        .S_AXI_WSTRB(s_axi_wstrb),",
        "        .S_AXI_WVALID(s_axi_wvalid),",
        "        .S_AXI_WREADY(s_axi_wready),",
        "        .S_AXI_BRESP(s_axi_bresp),",
        "        .S_AXI_BVALID(s_axi_bvalid),",
        "        .S_AXI_BREADY(s_axi_bready),",
        "        .S_AXI_ARADDR(s_axi_araddr),",
        "        .S_AXI_ARPROT(s_axi_arprot),",
        "        .S_AXI_ARVALID(s_axi_arvalid),",
        "        .S_AXI_ARREADY(s_axi_arready),",
        "        .S_AXI_RDATA(s_axi_rdata),",
        "        .S_AXI_RRESP(s_axi_rresp),",
        "        .S_AXI_RVALID(s_axi_rvalid),",
        "        .S_AXI_RREADY(s_axi_rready)",
        "    );",
        "",
        "    scheduler_core scheduler_core_u (",
        "        .clk(clk),",
        "        .rst(rst),",
        "        .axi_s_reg_bank(axi_s_reg_bank[31:0]),",
        "        .axi_s_feed_back(axi_s_feed_back),",
        "        .soft_rst(soft_rst),",
        "        .ins_rd_start(ins_rd_start),",
        "        .ins_rd_done(ins_rd_done),",
        "        .ins_fifo_rd_en(ins_fifo_rd_en),",
        "        .ins_fifo_n_empty(ins_fifo_n_empty),",
        "        .ins_fifo_data(ins_fifo_data),",
        "        .instruction(instruction),",
    ]
    for module in model.modules:
        if module.commands:
            lines.append(f"        .issue_{module.name}(issue_{module.name}),")
    lines.append("        .issue_regs(issue_regs),")
    for module in model.modules:
        if module.commands:
            lines.append(f"        .{module.name}_done({module.name}_ap_done),")
    lines += [
        "        .IRQ(IRQ)",
        "    );",
        "",
        "    // HLS-style start adapters: hold ap_start until ap_ready accepts it.",
    ]
    for module in model.modules:
        if module.commands:
            lines += [
                f"    always_ff @(posedge clk) begin",
                f"        if (soft_rst) begin",
                f"            {module.name}_ap_start <= 1'b0;",
                f"        end else begin",
                f"            if ({module.name}_ap_start && {module.name}_ap_ready)",
                f"                {module.name}_ap_start <= 1'b0;",
                f"            else if (issue_{module.name})",
                f"                {module.name}_ap_start <= 1'b1;",
                f"        end",
                f"    end",
                "",
            ]
    lines.append("    // Per-module command-state latches.")
    for module in model.modules:
        if not module.commands:
            continue
        arg_w = module_arg_width(module)
        lines += [
            "    always_ff @(posedge clk) begin",
            "        if (soft_rst) begin",
            f"            {module.name}_cmd_id <= '0;",
            f"            {module.name}_cmd_args <= '0;",
            f"        end else if (issue_{module.name}) begin",
            f"            {module.name}_cmd_id <= payload[{model.payload_width - 1}:{model.payload_width - module.command_id_width}];",
            f"            {module.name}_cmd_args <= '0;",
            f"            {module.name}_cmd_args[{arg_w - 1}:0] <= payload[{model.payload_width - module.command_id_width - 1}:{model.payload_width - module.command_id_width - arg_w}];",
            "        end",
            "    end",
            "",
        ]
    lines += [
        "    // Generated configuration registers.",
        "    always_ff @(posedge clk) begin",
        "        if (soft_rst) begin",
    ]
    for module in model.modules:
        for reg in module.regs:
            lines.append(f"            {module.name}_{reg.name} <= {packed_default(reg.fields)};")
    lines += [
        "        end else if (issue_regs) begin",
        "            case (reg_addr)",
    ]
    for module in model.modules:
        for reg in module.regs:
            lines += [
                f"                REG_{sv_const(module.name, reg.name)}: begin",
                f"                    {module.name}_{reg.name} <= payload[{model.payload_width - model.reg_addr_width - 1}:{model.payload_width - model.reg_addr_width - reg.packed_width}];",
                "                end",
            ]
    lines += [
        "                default: begin end",
        "            endcase",
        "        end",
        "    end",
        "endmodule",
        "",
    ]
    return "\n".join(lines)


def c_name(*parts: str) -> str:
    return "_".join(parts).lower()


def cpp_const(*parts: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in "_".join(parts).split("_") if part)


def cpp_type(field) -> str:
    if field.width > 64:
        return "Field128"
    prefix = "std::int" if field.signed else "std::uint"
    if field.width <= 8:
        return f"{prefix}8_t"
    if field.width <= 16:
        return f"{prefix}16_t"
    if field.width <= 32:
        return f"{prefix}32_t"
    return f"{prefix}64_t"


def cpp_pack_call(target: str, value: str, width: int, lsb: int) -> str:
    if width <= 64:
        return f"        detail::pack_u64({target}, static_cast<std::uint64_t>({value}), {width}, {lsb});"
    return f"        detail::pack_field128({target}, {value}, {width}, {lsb});"


def emit_cpp_header(model: Model) -> str:
    if model.instruction_width != 128:
        raise ValueError("C++ header emitter currently supports 128-bit instructions only")

    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace scheduler {",
        "",
        "struct Instruction {",
        "    std::uint64_t hi;",
        "    std::uint64_t lo;",
        "};",
        "",
        "using Field128 = Instruction;",
        "",
        "namespace detail {",
        "",
        "inline void pack_u64(Instruction &dst, std::uint64_t value, unsigned width, unsigned lsb)",
        "{",
        "    if (width == 0 || lsb >= 128)",
        "        return;",
        "",
        "    std::uint64_t masked = value;",
        "    if (width < 64)",
        "        masked &= ((UINT64_C(1) << width) - 1);",
        "",
        "    if (lsb < 64) {",
        "        unsigned lo_width = width;",
        "        if (lo_width > 64 - lsb)",
        "            lo_width = 64 - lsb;",
        "        const std::uint64_t lo_mask =",
        "            (lo_width == 64) ? UINT64_MAX : ((UINT64_C(1) << lo_width) - 1);",
        "        dst.lo |= (masked & lo_mask) << lsb;",
        "        if (width > lo_width)",
        "            dst.hi |= masked >> lo_width;",
        "    } else {",
        "        dst.hi |= masked << (lsb - 64);",
        "    }",
        "}",
        "",
        "inline void pack_field128(Instruction &dst, Field128 value, unsigned width, unsigned lsb)",
        "{",
        "    if (width <= 64) {",
        "        pack_u64(dst, value.lo, width, lsb);",
        "        return;",
        "    }",
        "    pack_u64(dst, value.lo, 64, lsb);",
        "    pack_u64(dst, value.hi, width - 64, lsb + 64);",
        "}",
        "",
        "inline Instruction make_instruction(std::uint64_t opcode)",
        "{",
        "    Instruction out = {0, 0};",
        f"    pack_u64(out, opcode, {model.opcode_width}, {model.payload_width});",
        "    return out;",
        "}",
        "",
    ]

    for op in model.system_ops:
        lines.append(f"constexpr std::uint64_t OpSys{cpp_const(op.name)} = 0x{op.opcode:X}ull;")
    if model.regs_opcode is not None:
        lines.append(f"constexpr std::uint64_t OpRegs = 0x{model.regs_opcode:X}ull;")
    for module in model.modules:
        if module.name in model.command_opcodes:
            lines.append(f"constexpr std::uint64_t OpCmd{cpp_const(module.name)} = 0x{model.command_opcodes[module.name]:X}ull;")
            for command in module.commands:
                lines.append(f"constexpr std::uint64_t Cmd{cpp_const(module.name, command.name)} = {command.command_id}ull;")
    for module in model.modules:
        for reg in module.regs:
            lines.append(f"constexpr std::uint64_t Reg{cpp_const(module.name, reg.name)} = {reg.addr}ull;")

    lines += [
        "",
        "} // namespace detail",
        "",
        "class Instructions {",
        "public:",
        "    Instructions(Instruction *data, std::uint32_t capacity, std::uint32_t device_addr)",
        "        : data_(data), size_(0), capacity_(capacity), device_addr_(device_addr)",
        "    {",
        "    }",
        "",
        "    Instruction *data() const { return data_; }",
        "    std::uint32_t size() const { return size_; }",
        "    std::uint32_t capacity() const { return capacity_; }",
        "    std::uint32_t remaining() const { return capacity_ - size_; }",
        "    std::uint32_t device_addr() const { return device_addr_; }",
        "    bool empty() const { return size_ == 0; }",
        "    bool full() const { return size_ >= capacity_; }",
        "",
        "    void clear()",
        "    {",
        "        size_ = 0;",
        "    }",
        "",
    ]

    for op in model.system_ops:
        lname = c_name(op.name)
        lines += [
            f"    bool {lname}()",
            "    {",
            f"        return push(detail::make_instruction(detail::OpSys{cpp_const(op.name)}));",
            "    }",
            "",
        ]

    for module in model.modules:
        for command in module.commands:
            args = [f"{cpp_type(field)} {c_name(field.name)}" for field in command.args]
            args_text = ", ".join(args)
            lines += [
                f"    bool launch_{c_name(module.name, command.name)}({args_text})",
                "    {",
                f"        Instruction inst = detail::make_instruction(detail::OpCmd{cpp_const(module.name)});",
                cpp_pack_call("inst", f"detail::Cmd{cpp_const(module.name, command.name)}", module.command_id_width, command.command_id_lsb),
            ]
            for placement in command.arg_layout:
                field = placement.field
                lines.append(cpp_pack_call("inst", c_name(field.name), field.width, placement.lsb))
            lines += [
                "        return push(inst);",
                "    }",
                "",
            ]

        for reg in module.regs:
            args = [f"{cpp_type(field)} {c_name(field.name)}" for field in reg.fields]
            args_text = ", ".join(args)
            lines += [
                f"    bool config_{c_name(module.name, reg.name)}({args_text})",
                "    {",
                "        Instruction inst = detail::make_instruction(detail::OpRegs);",
                cpp_pack_call("inst", f"detail::Reg{cpp_const(module.name, reg.name)}", model.reg_addr_width, reg.addr_lsb),
            ]
            for placement in reg.field_layout:
                field = placement.field
                lines.append(cpp_pack_call("inst", c_name(field.name), field.width, placement.lsb))
            lines += [
                "        return push(inst);",
                "    }",
                "",
            ]

    lines += [
        "private:",
        "    bool push(Instruction instruction)",
        "    {",
        "        if (full())",
        "            return false;",
        "        data_[size_++] = instruction;",
        "        return true;",
        "    }",
        "",
        "    Instruction *data_;",
        "    std::uint32_t size_;",
        "    std::uint32_t capacity_;",
        "    std::uint32_t device_addr_;",
        "};",
        "",
        "enum class State {",
        "    Idle,",
        "    Working,",
        "    Resetting,",
        "};",
        "",
        "class FpgaScheduler {",
        "public:",
        "    explicit FpgaScheduler(std::uintptr_t base_addr)",
        "        : regs_(reinterpret_cast<volatile std::uint32_t *>(base_addr)),",
        "          bytes_(reinterpret_cast<volatile std::uint8_t *>(base_addr)),",
        "          valid_(hw_version() == ExpectedHwVersion)",
        "    {",
        "        reset_blocking();",
        "    }",
        "",
        "    explicit FpgaScheduler(volatile void *base_addr)",
        "        : FpgaScheduler(reinterpret_cast<std::uintptr_t>(base_addr))",
        "    {",
        "    }",
        "",
        "    bool valid() const",
        "    {",
        "        return valid_;",
        "    }",
        "",
        "    void set_irq(bool enable) const",
        "    {",
        "        std::uint8_t cfg = bytes_[1];",
        "        if (enable)",
        "            cfg = static_cast<std::uint8_t>(cfg | CfgIrqEnable);",
        "        else",
        "            cfg = static_cast<std::uint8_t>(cfg & ~CfgIrqEnable);",
        "        bytes_[1] = cfg;",
        "    }",
        "",
        "    void run(const Instructions &instructions) const",
        "    {",
        "        run(instructions.device_addr(), instructions.size());",
        "    }",
        "",
        "    void run(std::uint32_t instruction_addr, std::uint32_t instruction_count) const",
        "    {",
        "        regs_[RegInstrBase] = instruction_addr;",
        "        regs_[RegInstrCount] = instruction_count;",
        "        bytes_[0] = ReqStart;",
        "    }",
        "",
        "    State get_state() const",
        "    {",
        "        const std::uint32_t ctrl = regs_[RegCtrl];",
        "        if ((ctrl & StateResetting) != 0u)",
        "            return State::Resetting;",
        "        if ((ctrl & StateWorking) != 0u)",
        "            return State::Working;",
        "        return State::Idle;",
        "    }",
        "",
        "    bool check_state(State state) const",
        "    {",
        "        return get_state() == state;",
        "    }",
        "",
        "    bool is_busy() const",
        "    {",
        "        return get_state() != State::Idle;",
        "    }",
        "",
        "    std::uint8_t hw_version() const",
        "    {",
        "        return static_cast<std::uint8_t>((regs_[RegCtrl] >> 24) & 0xffu);",
        "    }",
        "",
        "private:",
        "    static constexpr std::uint8_t ExpectedHwVersion = 1;",
        "    static constexpr std::uint32_t RegCtrl = 0;",
        "    static constexpr std::uint32_t RegInstrBase = 1;",
        "    static constexpr std::uint32_t RegInstrCount = 2;",
        "    static constexpr std::uint8_t ReqReset = 1u << 0;",
        "    static constexpr std::uint8_t ReqStart = 1u << 1;",
        "    static constexpr std::uint8_t CfgIrqEnable = 1u << 0;",
        "    static constexpr std::uint32_t StateWorking = 1u << 16;",
        "    static constexpr std::uint32_t StateResetting = 1u << 17;",
        "",
        "    void reset_blocking() const",
        "    {",
        "        bytes_[0] = ReqReset;",
        "        while ((bytes_[0] & ReqReset) != 0u) {",
        "        }",
        "    }",
        "",
        "    volatile std::uint32_t *regs_;",
        "    volatile std::uint8_t *bytes_;",
        "    bool valid_;",
        "};",
        "",
        "} // namespace scheduler",
        "",
    ]
    return "\n".join(lines)


def write_outputs(model: Model, outdir: Path, repo_root: Path) -> list[str]:
    outdir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "scheduler_core.sv": emit_core(model),
        "scheduler_wrapper.sv": emit_wrapper(model),
        "scheduler_control.hpp": emit_cpp_header(model),
    }
    for name, content in outputs.items():
        (outdir / name).write_text(content)

    template_dir = Path(__file__).resolve().parents[1] / "template"
    axi_src = template_dir / "scheduler_ctrl_axi_lite.sv"
    if not axi_src.exists():
        raise FileNotFoundError(f"missing AXI-lite template: {axi_src}")
    shutil.copyfile(axi_src, outdir / "scheduler_ctrl_axi_lite.sv")
    return list(outputs.keys()) + ["scheduler_ctrl_axi_lite.sv"]
